/** Çalışma listesi — yeni modül eklenince ve durum değişince Cursor günceller. */
window.HBC_CALISMALAR = [
  {
    id: 'taskin_dashboard',
    label: 'Taşkın Dashboard',
    desc: 'Taşkın Dashboard',
    eklendi: '2026-08-06',
    menuYer: 'sol',
    durum: 'task-hazir',
    mockupSayisi: 1,
    taskBe: 10,
    taskFe: 7,
    onay: { tarih: '2026-08-06', kim: 'Hazal' },
    icon: '📁'
  },
  {
    id: 'genel_dashboard',
    label: 'Genel Dashboard',
    desc: 'Yönetici Ekranı',
    eklendi: '2026-07-30',
    menuYer: 'sol',
    durum: 'mockup-taslak',
    mockupSayisi: 0,
    taskBe: 0,
    taskFe: 0,
    icon: '📁'
  },
  {
    id: 'iklim',
    label: 'IKLIM',
    desc: 'İklim Yönetimi Dashboard',
    eklendi: '2026-07-30',
    menuYer: 'sol',
    durum: 'task-hazir',
    mockupSayisi: 1,
    taskBe: 8,
    taskFe: 7,
    onay: { tarih: '2026-08-10', kim: 'Hazal' },
    icon: '📁'
  },
  {
    id: 'kaynaktan_musluga',
    label: 'Kaynaktan Musluğa',
    desc: 'Su kaynağı, tesis ve musluk — örnek çalışma',
    eklendi: '2026-01-10',
    durum: 'task-hazir',
    mockupSayisi: 7,
    taskBe: 10,
    taskFe: 7,
    onay: { tarih: '2026-06-23', kim: 'Hazal' },
    icon: '📁',
    ornek: true
  },
  {
    id: 'su_kalitesi_raporu',
    label: 'Su Kalitesi Özeti',
    desc: 'Salt okunur rapor — örnek',
    eklendi: '2026-02-05',
    durum: 'task-hazir',
    mockupSayisi: 1,
    taskBe: 1,
    taskFe: 1,
    onay: { tarih: '2026-06-23', kim: 'Hazal' },
    icon: '📊',
    ornek: true,
    ornekRapor: true
  },
  {
    id: 'taslak_demo',
    label: 'Taslak Demo',
    desc: 'Liste, form, rapor ve üst menü — örnek · tüm türler',
    eklendi: '2026-03-15',
    menuYer: 'ust',
    durum: 'task-hazir',
    mockupSayisi: 7,
    taskBe: 9,
    taskFe: 7,
    onay: { tarih: '2026-06-23', kim: 'Hazal' },
    icon: '📁',
    ornek: true,
    ornekTumTurler: true
  },
  {
    id: 'yazi_olustur',
    label: 'Yazı Oluştur',
    desc: 'Kurumsal görüş yazısı — Excel makro programının web karşılığı',
    eklendi: '2026-06-20',
    menuYer: 'sol',
    durum: 'task-hazir',
    mockupSayisi: 4,
    taskBe: 9,
    taskFe: 4,
    onay: { tarih: '2026-06-30', kim: 'Hazal' },
    icon: '📝'
  },
  {
    id: 'hidromorfolojik_baski',
    label: 'Hidromorfolojik Baskı',
    desc: 'Hidromorfolojik Baskı',
    eklendi: '2026-07-01',
    menuYer: 'sol',
    durum: 'task-hazir',
    mockupSayisi: 2,
    taskBe: 4,
    taskFe: 2,
    onay: { tarih: '2026-07-01', kim: 'Hazal' },
    icon: '📁'
  }
];
